/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) test_interp_acados_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_flip CASADI_PREFIX(flip)
#define casadi_interpn CASADI_PREFIX(interpn)
#define casadi_interpn_grad CASADI_PREFIX(interpn_grad)
#define casadi_interpn_interpolate CASADI_PREFIX(interpn_interpolate)
#define casadi_interpn_weights CASADI_PREFIX(interpn_weights)
#define casadi_low CASADI_PREFIX(low)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_interpn_weights(casadi_int ndim, const casadi_real* grid, const casadi_int* offset, const casadi_real* x, casadi_real* alpha, casadi_int* index, const casadi_int* lookup_mode) {
  casadi_int i;
  for (i=0; i<ndim; ++i) {
    casadi_int ng, j;
    casadi_real xi;
    const casadi_real* g;
    xi = x ? x[i] : 0;
    g = grid + offset[i];
    ng = offset[i+1]-offset[i];
    j = index[i] = casadi_low(xi, g, ng, lookup_mode[i]);
    alpha[i] = (xi-g[j])/(g[j+1]-g[j]);
  }
}

void casadi_interpn_interpolate(casadi_real* res, casadi_int ndim, const casadi_int* offset, const casadi_real* values, const casadi_real* alpha, const casadi_int* index, const casadi_int* corner, casadi_real* coeff, casadi_int m) {
  casadi_real c;
  casadi_int ld, i;
  c=1;
  ld=1;
  for (i=0; i<ndim; ++i) {
    if (coeff) *coeff++ = c;
    if (corner[i]) {
      c *= alpha[i];
    } else {
      c *= 1-alpha[i];
    }
    values += (index[i]+corner[i])*ld*m;
    ld *= offset[i+1]-offset[i];
  }
  if (coeff) {
    for (i=0;i<m;++i) res[i] += values[i];
  } else {
    for (i=0;i<m;++i) res[i] += c*values[i];
  }
}

casadi_int casadi_flip(casadi_int* corner, casadi_int ndim) {
  casadi_int i;
  for (i=0; i<ndim; ++i) {
    if (corner[i]) {
      corner[i]=0;
    } else {
      corner[i]=1;
      return 1;
    }
  }
  return 0;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_interpn(casadi_real* res, casadi_int ndim, const casadi_real* grid, const casadi_int* offset, const casadi_real* values, const casadi_real* x, const casadi_int* lookup_mode, casadi_int m, casadi_int* iw, casadi_real* w) {
  casadi_real* alpha;
  casadi_int *index, *corner;
  alpha = w; w += ndim;
  index = iw; iw += ndim;
  corner = iw; iw += ndim;
  casadi_interpn_weights(ndim, grid, offset, x, alpha, index, lookup_mode);
  casadi_clear_casadi_int(corner, ndim);
  casadi_clear(res, m);
  do {
    casadi_real* coeff = 0;
    casadi_interpn_interpolate(res, ndim, offset, values,
      alpha, index, corner, coeff, m);
  } while (casadi_flip(corner, ndim));
}

void casadi_interpn_grad(casadi_real* grad, casadi_int ndim, const casadi_real* grid, const casadi_int* offset, const casadi_real* values, const casadi_real* x, const casadi_int* lookup_mode, casadi_int m, casadi_int* iw, casadi_real* w) {
  casadi_real *alpha, *coeff, *v;
  casadi_int *index, *corner;
  casadi_int i;
  if (!grad) return;
  alpha = w; w += ndim;
  coeff = w; w += ndim;
  v = w; w+= m;
  index = iw; iw += ndim;
  corner = iw; iw += ndim;
  casadi_interpn_weights(ndim, grid, offset, x, alpha, index, lookup_mode);
  casadi_clear_casadi_int(corner, ndim);
  casadi_clear(grad, ndim*m);
  do {
    casadi_int i, j;
    casadi_clear(v, m);
    casadi_interpn_interpolate(v, ndim, offset, values,
      alpha, index, corner, coeff, m);
    for (i=ndim-1; i>=0; --i) {
      if (corner[i]) {
        for (j=0; j<m; ++j) {
          grad[i*m+j] += v[j]*coeff[i];
          v[j] *= alpha[i];
        }
      } else {
        for (j=0; j<m; ++j) {
          grad[i*m+j] -= v[j]*coeff[i];
          v[j] *= 1-alpha[i];
        }
      }
    }
  } while (casadi_flip(corner, ndim));
  for (i=0; i<ndim; ++i) {
    casadi_int k, j;
    const casadi_real* g;
    casadi_real delta;
    g = grid + offset[i];
    j = index[i];
    delta =  g[j+1]-g[j];
    for (k=0;k<m;++k) grad[k] /= delta;
    grad += m;
  }
}

static const casadi_int casadi_s0[1] = {0};
static const casadi_int casadi_s1[2] = {0, 3};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {0, 1, 1};

static const casadi_real casadi_c0[3] = {5.5000000000000000e-02, 1.0000000000000000e-02, -1.2999999999999999e-02};
static const casadi_real casadi_c1[3] = {5.0000000000000003e-02, 6.6700000000000004e-01, 8.3299999999999996e-01};

/* interp_test:(x)->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    if (res[0]) {
        casadi_interpn(res[0], 1, casadi_c1, casadi_s1, casadi_c0, arg[0], casadi_s0, 1, iw, w);
      }
  return 0;
}

/* jac_interp_test:(x,out_f[1x1,0nz])->(jac_f_x) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
    casadi_interpn_grad(res[0], 1, casadi_c1, casadi_s1, casadi_c0, arg[0], casadi_s0,1, iw, w);
  return 0;
}

/* fwd1_wrap_interp_test:(x,out_f[1x1,0nz],fwd_x)->(fwd_f) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, w0, w2;
  const casadi_real **arg1=arg+3;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = 00 */
  /* #2: @2 = jac_interp_test(@0, @1) */
  arg1[0]=(&w0);
  arg1[1]=0;
  res1[0]=(&w2);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #3: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #4: @2 = (@2*@0) */
  w2 *= w0;
  /* #5: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  return 0;
}

/* test_interp_acados_expl_vde_forw:(i0,i1,i2,i3,i4[0])->(o0,o1,o2) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a2, a3, a4;
  a0=arg[0]? arg[0][0] : 0;
  arg[5] = arg[3]? arg[3] + 0 : 0;
  res[3]=w+1;
  if (casadi_f1(arg+5, res+3, iw, w+2, 0)) return 1;
  a2 = w[1];
  a2=(a0+a2);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[1]? arg[1][0] : 0;
  a3=0.;
  arg[5] = arg[3]? arg[3] + 0 : 0;
  arg[6]=0;
  arg[7]=w+1;
  res[3]=w+2;
  w[1] = a3;
  if (casadi_f2(arg+5, res+3, iw, w+3, 0)) return 1;
  a3 = w[2];
  a2=(a2+a3);
  if (res[1]!=0) res[1][0]=a2;
  a2=1.;
  arg[5] = arg[3]? arg[3] + 0 : 0;
  arg[6]=0;
  arg[7]=w+1;
  res[3]=w+2;
  w[1] = a2;
  if (casadi_f2(arg+5, res+3, iw, w+3, 0)) return 1;
  a2 = w[2];
  a4=arg[2]? arg[2][0] : 0;
  a4=(a4+a3);
  a2=(a2+a4);
  if (res[2]!=0) res[2][0]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int test_interp_acados_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int test_interp_acados_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int test_interp_acados_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void test_interp_acados_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int test_interp_acados_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void test_interp_acados_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void test_interp_acados_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void test_interp_acados_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int test_interp_acados_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int test_interp_acados_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real test_interp_acados_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* test_interp_acados_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* test_interp_acados_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* test_interp_acados_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s2;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* test_interp_acados_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s2;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int test_interp_acados_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 8;
  return 0;
}

CASADI_SYMBOL_EXPORT int test_interp_acados_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 4*sizeof(casadi_int);
  if (sz_w) *sz_w = 8*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
